### ISSUE TITLE
Game Crash on lobby load after successful heist.

### ISSUE THREAD

**Issue by BarclayTech** [zenyr/PocoHud3#18]
Can't say the same after a failed Pro Job but yeah. The game crashes when the lobby loads after a successful heist. Happens 100% of the time.

**Comment by goontest** [comment]
Same issue as above

**Comment by gregmac** [comment]
Looks like a potential fix for this in 32c5729

**Comment by zenyr** [comment]
not really, see forum and try arkkat's fix at the moment. it will disable
"auto restart" for HUD so apply options button will be broken. But you can
use it if you don't hit that apply button. :p

2015년 3월 19일 목요일, Greg MacLellan<notifications@github.com>님이 작성한 메시지:

> Looks like a potential fix for this in 32c5729
> <https://github.com/zenyr/PocoHud3/commit/32c5729aeeaa7fc36c76cbc3837baf9691dbf407>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zenyr/PocoHud3/issues/18#issuecomment-83239582>.
>


-- 
- Zenyr
http://zenyr.com, http://zenyrskin.innori.com
