### ISSUE TITLE
Job statistics broken since latest update

### ISSUE THREAD

**Issue by Hexicube** [zenyr/PocoHud3#25]
Line containing error: Hud3_class:2595
"for no,heist in _.p(job_list) do"

Actual offending code: Hud3_class:2556
"local host_list, level_list, job_list, mask_list, weapon_list = tweak_data.achievement.job_list, tweak_data.statistics:statistics_table()"

I think this started happening when the recent update came out. It breaks the job statistics page.

**Comment by zenyr** [comment]
(forgot to answer this) Yep, indeed, r383 would fix this. Check the latest master branch / dropbox download page! 

My auto deployment process was borked(while migrating to windows 10) so I had to hand-label last commit though. :sun_with_face:
