### ISSUE TITLE
[Request] Ability to choose what songs you want auto shuffle to play

### ISSUE THREAD

**Issue by Hexicube** [zenyr/PocoHud3#26]
I like most of the PD2 soundtrack, and I like the functionality auto shuffle provides, however I'd like to be able to tell PocoHud I don't want to hear specific songs.

I'd imagine this functionality would be best implemented in the jukebox panel, as you can listen to the music there. Something as simple as a check-box next to the song name in the list would work well.

**Comment by zenyr** [comment]
This feature obeys the vanilla game configuration. In other words, the feature calls the exact same logic to fetch a music when you restart a game. :smile: 

If this is not the case, please re-open this issue!

**Comment by Hexicube** [comment]
Ah, wasn't even aware you could do that in the base game...
