### ISSUE TITLE
[Feature Request] - BLT-style mod options menu

### ISSUE THREAD

**Issue by karasuhebi** [zenyr/PocoHud3#31]
Now that you guys are officially a BLT mod, could we have an in-game menu that's part of the Mod Options submenu? I'd love to have a way to edit PocoHud's options while in-game.

Thanks! :D

**Comment by karasuhebi** [comment]
Would still love to see this implemented. Any news?

**Comment by zenyr** [comment]
it must be quite crowded eh, I had made the panel to circumvent usability issue(replacing that with another accessibility issue) so.. not planned at the moment.
