### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by drewofdoom** [zenyr/PocoHud3#35]
PocoMod is currently not properly working in Arch Linux. Would like some other Linux users on other distros to test and confirm.

Steam outputs this error when trying to load the mod:
`Err: Failed to load mods/PocoHud3/poco/../poco/3rdPartyLibrary.luacErr: Failed to load mods/PocoHud3/poco/../poco/Hud3_class.luacErr: Failed to load mods/PocoHud3/poco/../poco/Hud3_Options.luacErr: Failed to load mods/PocoHud3/poco/../poco/Hud3.luacPoco:Init`

At first I thought this was due to file naming issues, as Linux is case-sensitive, but that does not appear to be the case from glancing at the code.

Using the [BLT4L](https://github.com/blt4linux/blt4l) Linux hook.

**Comment by drewofdoom** [comment]
This should have been left on [Kilandor's branch](https://github.com/Kilandor/PocoHud3) instead.

**Comment by zenyr** [comment]
Hmm interesting, did not have a chance to test on linux system. Let me know if I have something to help.
