### ISSUE TITLE
Some request about language localization

### ISSUE THREAD

**Issue by dog194** [zenyr/PocoHud3#57]
Hello. 

**Would mind changing the function Localizer:get(key,context) in Hud3_class.lua?** 

At line 4151
From 
local val = _defaultLocaleData[key] or self.data[key] or self._data[key] or PocoHud3Class.Icon[key:gsub('_','')]  
To 
local val = self.data[key] or _defaultLocaleData[key] or self._data[key] or PocoHud3Class.Icon[key:gsub('_','')]

Just change the priority of detaultLocaleData and selfdata (For localization). That we can change the message and mod name to other language.

**If you do not agree.Here is an alternative solution:**
 
Just move the _mob and _msg from _defaultLocaleData to hud3_localeEN.json file.

**Comment by zenyr** [comment]
Hmm it's okay I guess, you can send me a PR if you want! I used to be opinionated about them(pocorose and whatnot) but I do not mind it anymore.

**Comment by dog194** [comment]
Thank you very much！
