### ISSUE TITLE
pocohud mod crash 

### ISSUE THREAD

**Issue by BearThatRun** [zenyr/PocoHud3#64]
Thu Apr 26 18:11:24 2018

Application has crashed: C++ exception
[string "lib/network/handlers/unitnetworkhandler.lua"]:2830: attempt to perform arithmetic on a nil value

SCRIPT STACK

@mods/PocoHud3/poco/../poco/Hud3.lua:2171

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by steklo** [comment]
change variable
"minion_owner_peer_id"
for
"peerId"
twice of them

**Comment by BearThatRun** [comment]
> 
i know its kinda late, but i wanted to say thank you <3
