### ISSUE TITLE
how do i change the keybind for opening the menu

### ISSUE THREAD

**Issue by tobie-d** [zenyr/PocoHud3#69]
the backspace is so annoying how do i change it

**Comment by zenyr** [comment]
It should be this line, Change the number `14` to something else to change it. (not sure of which number corresponds to which key atm, sorry 😅 )
https://github.com/zenyr/PocoHud3/blob/master/poco/Hud3.lua#L649-L651
If you're never going to open the PocoHud menu anyways (for example you've set your configuration just right) you can comment out the line. Add double dashes before those 3 lines to completely disable the menu.

```lua
-- Poco:Bind(self,14,function()
--	self:Menu(false,false)
-- end)
```
